services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: petsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - petsdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  petsdata:
